# Generated by Django 4.1.5 on 2023-01-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizard',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
